package mybatis.model;

public class TNginxGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nginx_group.nginxGroupId
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    private Integer nginxgroupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nginx_group.groupName
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nginx_group.registryId
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    private Integer registryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nginx_group.version
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nginx_group.resolver
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    private String resolver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nginx_group.parentVersion
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    private Long parentversion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nginx_group.nginxGroupId
     *
     * @return the value of t_nginx_group.nginxGroupId
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    public Integer getNginxgroupid() {
        return nginxgroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nginx_group.nginxGroupId
     *
     * @param nginxgroupid the value for t_nginx_group.nginxGroupId
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    public void setNginxgroupid(Integer nginxgroupid) {
        this.nginxgroupid = nginxgroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nginx_group.groupName
     *
     * @return the value of t_nginx_group.groupName
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nginx_group.groupName
     *
     * @param groupname the value for t_nginx_group.groupName
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nginx_group.registryId
     *
     * @return the value of t_nginx_group.registryId
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    public Integer getRegistryid() {
        return registryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nginx_group.registryId
     *
     * @param registryid the value for t_nginx_group.registryId
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    public void setRegistryid(Integer registryid) {
        this.registryid = registryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nginx_group.version
     *
     * @return the value of t_nginx_group.version
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nginx_group.version
     *
     * @param version the value for t_nginx_group.version
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nginx_group.resolver
     *
     * @return the value of t_nginx_group.resolver
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    public String getResolver() {
        return resolver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nginx_group.resolver
     *
     * @param resolver the value for t_nginx_group.resolver
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    public void setResolver(String resolver) {
        this.resolver = resolver == null ? null : resolver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nginx_group.parentVersion
     *
     * @return the value of t_nginx_group.parentVersion
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    public Long getParentversion() {
        return parentversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nginx_group.parentVersion
     *
     * @param parentversion the value for t_nginx_group.parentVersion
     *
     * @mbggenerated Wed Jul 19 15:57:12 CST 2017
     */
    public void setParentversion(Long parentversion) {
        this.parentversion = parentversion;
    }
}